name: crypto_keys
description: A library for doing cryptographic signing/verifying and encrypting/decrypting.
version: 0.3.0+1
homepage: https://github.com/appsup-dart/crypto_keys
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pointycastle: ^3.6.2
  meta: ^1.3.0
  collection: ^1.14.13
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.16.2
  lints: ^2.0.0
