name: crypto_keys
description: A library for doing cryptographic signing/verifying and encrypting/decrypting.
version: 0.3.0+2
homepage: https://github.com/appsup-dart/crypto_keys
funding:
  - https://github.com/sponsors/rbellens

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  pointycastle: ^4.0.0
  meta: ^1.3.0
  collection: ^1.14.13
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.16.2
  lints: ^5.1.1
  melos: ^6.3.2
