name: crypto_keys
description: A library for doing cryptographic signing/verifying and encrypting/decrypting.
version: 0.1.3
homepage: https://github.com/appsup-dart/crypto_keys

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pointycastle: ^1.0.0
  meta: ^1.1.6
  collection: ^1.14.13
  quiver: ^2.1.5

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
