name: crypto_keys
description: A library for doing cryptographic signing/verifying and encrypting/decrypting.
version: 0.2.0-nullsafety.2
homepage: https://github.com/appsup-dart/crypto_keys

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  pointycastle: ^3.0.0-nullsafety.2
  meta: ^1.3.0
  collection: ^1.14.13
  quiver: ^3.0.0-nullsafety.3

dev_dependencies:
  test: ^1.16.2
  pedantic: ^1.10.0
